#!/bin/bash -l
#PBS -l walltime=01:00:00,mem=8gb,nodes=1:ppn=8
#PBS -o /scratch.global/waters/trimmomatic_test_jackie_o_file
#PBS -e /scratch.global/waters/trimmomatic_test_jackie_e_file

module load trimmomatic
module load fastqc

date

java -Xmx7000M -jar $TRIMMOMATIC/trimmomatic.jar PE -basein /home/springer/nosha003/schmitz/atacseq/fastq/JN13_ATAC_S1_R1_001.fastq.gz -baseout /scratch.global/waters/B73_Root_rep1.fastq ILLUMINACLIP:$TRIMMOMATIC/adapters/all_illumina_adapters.fa:2:30:10:2:true LEADING:20 TRAILING:20 SLIDINGWINDOW:4:20 MINLEN:35

#java -Xmx7000M -jar $TRIMMOMATIC/trimmomatic.jar PE -basein /home/pepsico/data_release/umgc/hiseq/160621_SN1073_0580_AHTWGHBCXX/PepsiCo_Project_062/${FILE1} -baseout trimmed_reads/${FILE2} ILLUMINACLIP:$TRIMMOMATIC/adapters/all_illumina_adapters.fa:2:30:10:2:true LEADING:20 TRAILING:20 SLIDINGWINDOW:4:20 MINLEN:150

#date

#echo "fastqc -o fastqc trimmed_reads/${FILE3}_1P.fastq"
#fastqc -o fastqc trimmed_reads/${FILE3}_1P.fastq

#date

#echo "fastqc -o fastqc trimmed_reads/${FILE3}_2P.fastq"
#fastqc -o fastqc trimmed_reads/${FILE3}_2P.fastq

#date

echo "finished"
